# Generated by Django 4.1.4 on 2023-01-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcommunce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=50, null=True)),
                ('khmer', models.CharField(max_length=255, null=True)),
                ('english', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblcomunce',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tbldistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=50, null=True)),
                ('khmer', models.CharField(max_length=255, null=True)),
                ('english', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbldistrict',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tblprovinc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=50, null=True)),
                ('khmer', models.CharField(max_length=255, null=True)),
                ('english', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblprovinc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tblvillages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('english', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblvillages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tblcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=200)),
                ('image', models.ImageField(default='customer/dfcustomer.jpg', upload_to='customer')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('communce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communce', to='food_menu.tblcommunce')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='food_menu.tbldistrict')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='food_menu.tblprovinc')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village', to='food_menu.tblvillages')),
            ],
            options={
                'db_table': 'tblcustomer',
                'ordering': ['-create_date'],
            },
        ),
    ]
