# Generated by Django 4.1.4 on 2023-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblvillages',
            old_name='description',
            new_name='khmer',
        ),
    ]
