# Generated by Django 4.1.4 on 2023-01-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsupplyer',
            name='inputer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='food_menu.tblprovince', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village', to='food_menu.tblvillages', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commune_cus', to='food_menu.tblcommunce', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_cus', to='food_menu.tbldistrict', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='inputer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputer_cus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cus', to='food_menu.tblprovince', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_cus', to='food_menu.tblvillages', to_field='uniqid'),
        ),
    ]
