# Generated by Django 4.1.4 on 2023-01-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0003_rename_tblprovinc_tblprovince_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblprovince',
            table='tblprovince',
        ),
    ]
