# Generated by Django 4.1.4 on 2023-01-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0004_alter_tblprovince_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblcommunce',
            table='tblcommunce',
        ),
    ]
