# Generated by Django 4.1.4 on 2023-01-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_menu', '0005_alter_tblcommunce_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblsupplyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=225, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblsupplyer',
            },
        ),
        migrations.AlterField(
            model_name='tblcommunce',
            name='uniqid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbldistrict',
            name='uniqid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tblprovince',
            name='uniqid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tblvillages',
            name='uniqid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='tblcustomer',
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commune', to='food_menu.tblcommunce', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='food_menu.tbldistrict', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='inputer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='food_menu.tblprovince', to_field='uniqid'),
        ),
        migrations.AddField(
            model_name='tblsupplyer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village', to='food_menu.tblvillages', to_field='uniqid'),
        ),
    ]
