# Generated by Django 4.1.4 on 2023-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0006_tblsupplyer_alter_tblcommunce_uniqid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsupplyer',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='supplyer'),
        ),
    ]
