# Generated by Django 4.1.4 on 2023-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0007_tblsupplyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsupplyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tblsupplyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
