# Generated by Django 4.1.4 on 2023-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0010_alter_tblsupplyer_commune_alter_tblsupplyer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsupplyer',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to='supplyer'),
        ),
    ]
