# Generated by Django 4.1.4 on 2023-01-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_menu', '0011_alter_tblsupplyer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='user.png', upload_to='supplyer')),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commune_cus', to='food_menu.tblcommunce', to_field='uniqid')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_cus', to='food_menu.tbldistrict', to_field='uniqid')),
                ('inputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputer_cus', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cus', to='food_menu.tblprovince', to_field='uniqid')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_cus', to='food_menu.tblvillages', to_field='uniqid')),
            ],
            options={
                'db_table': 'tblcustomer',
            },
        ),
    ]
